#'Fishing Mortality Table
#'
#'Creates a table of fishing mortalities by species group and gear for an Rpath.sim object.
#'
#'@family Rpath functions
#'
#'@param Rsim.scenario Object generated by rsim.scenario.
#'
#'@return Returns a data table of F values for each species/gear combination.
#'@export 
frate.table <- function(Rsim.scenario){
  fish <- data.table(Group = Rsim.scenario$params$FishFrom,
                     Gear  = Rsim.scenario$params$FishThrough,
                     Q     = Rsim.scenario$params$FishQ)
  group <- unique(fish[Group > 0, Group])
  gear  <- unique(fish[Gear  > 0, Gear])
  
  group.name <- Rsim.scenario$params$spname[unique(fish[Group > 0, Group]) + 1]
  gear.name  <- Rsim.scenario$params$spname[unique(fish[Gear  > 0, Gear ]) + 1]
  
  fish.out <- c()
  for(i in 1:length(group)){
    fish.group <- fish[Group == group[i], ]
    fish.all.gear <- data.table(Group = group.name[i])
    for(j in 1:length(gear)){
      f.gear <- data.table(Group = group.name[i], V1 = fish.group[Gear == gear[j], sum(Q)])
      setnames(f.gear, 'V1', gear.name[j])
      fish.all.gear <- merge(fish.all.gear, f.gear, by = 'Group')
    }
    fish.out <- rbindlist(list(fish.out, fish.all.gear))
  }
  fish.out[, Total := rowSums(.SD), .SDcols = gear.name]
  return(fish.out)
}

#'Adjust Fishing Mortality
#'
#'Modifies the fishing mortality value for a species by a particular gear.
#'
#'@family Rpath functions
#'
#'@param Rsim.scenario Object generated by ecosim.scenario.
#'@param parameter One of three parameters to be modified: EFFORT, FRATE, or CATCH
#'@param group Name or number of the species group whose fishing parameter is being changed.
#'@param gear Name or number of the gear to which the change applies.
#'@param year Year of the simulation that should be modified.  Can be a range of years.
#'@param value New value for the parameter.
#'
#'@return Returns an Rpath.sim object with the new fishing parameter.
#'@export 
adjust.fishing <- function(Rsim.scenario, parameter, group = NA, gear = NA, 
                           year, value){
  #Lookup gear/group numbers
  if(!is.na(group)){
    groupnum <- Rsim.scenario$params$spnum[which(Rsim.scenario$params$spname 
                                                 == group)]
  }
  if(!is.na(gear)){
    gearnum <- Rsim.scenario$params$spnum[which(Rsim.scenario$params$spname
                                                == gear)]
    gearnum <- gearnum - (Rsim.scenario$params$NUM_LIVING + 
                            Rsim.scenario$params$NUM_DEAD)
  }
  
  #Lookup parameter number
  param.num <- which(names(Rsim.scenario$fishing) == parameter)
  
  #Modify parameter
  if(parameter == 'EFFORT'){
    Rsim.scenario$fishing$EFFORT[year + 1, gearnum + 1] <- value
  }
  if(parameter %in% c('FRATE', 'CATCH')){
    Rsim.scenario$fishing[[param.num]][year + 1, groupnum + 1] <- value
  }
  return(Rsim.scenario)
}



#'Adjust Rsim.scenario parameters
#'
#'Modifies the various parameters of the rsim scenario object.
#'
#'@family Rpath functions
#'
#'@param Rsim.scenario Object generated by rsim.scenario.
#'@param parameter The Rsim.scenario parameter to be modified. (Create a table)
#'@param group The model group that the parameter change will affect.  Note that 
#'       a value of 'all' will affect all groups associate with the groupto
#'       variable.
#'@param groupto The coresponding group who's parameter is affecting the group
#'       variable.
#'@param value The new value for the parameter.
#'@return Returns an Rsim.scenario object with the new parameter.
#'@export 
adjust.scenario <- function(Rsim.scenario, parameter, group, groupto = NA, value){
  #Lookup group numbers
  if(group == 'all'){
    groupnum <- 1:Rsim.scenario$params$NUM_GROUPS
  } else {
    groupnum <- Rsim.scenario$params$spnum[which(Rsim.scenario$params$spname 
                                                 == group)]
  }
  if(!is.na(groupto)){
    groupnumto <- Rsim.scenario$params$spnum[which(Rsim.scenario$params$spname 
                                                 == groupto)]
  }
  
  #Lookup parameter number
  param.num <- which(names(Rsim.scenario$params) == parameter)
  
  #Modify parameter
  if(parameter %in% c('B_BaseRef', 'MzeroMort', 'UnassimRespFrac', 'ActiveRespFrac',
                      'FtimeAdj', 'FtimeQBOpt', 'PBopt', 'fish_Effort', 
                      'NoIntegrate', 'HandleSelf', 'ScrambleSelf')){
    Rsim.scenario$params[[param.num]][groupnum + 1] <- value
  }
  
  if(parameter %in% c('QQ', 'DD', 'VV', 'HandleSwitch', 'PredPredWeight', 
                      'PreyPreyWeight', 'PredTotWeight', 'PreyTotWeight')){
      linknum <- which(Rsim.scenario$params$PreyFrom %in% groupnum &
                         Rsim.scenario$params$PreyTo == groupnumto)  
    Rsim.scenario$params[[param.num]][linknum] <- value
  }
  return(Rsim.scenario)
}
 

