#'Fishing Mortality Table
#'
#'Creates a table of fishing mortalities by species group and gear for an Rpath.sim object.
#'
#'@family Rpath functions
#'
#'@param Rpath.sim Object generated by ecosim.init.
#'
#'@return Returns a data table of F values for each species/gear combination.
#'@export 
frate.table <- function(Rpath.sim){
  fish <- data.table(Group = Rpath.sim$FishFrom,
                     Gear  = Rpath.sim$FishThrough,
                     Q     = Rpath.sim$FishQ)
  group <- unique(fish[Group > 0, Group])
  gear  <- unique(fish[Gear  > 0, Gear])
  
  group.name <- Rpath.sim$spname[unique(fish[Group > 0, Group]) + 1]
  gear.name  <- Rpath.sim$spname[unique(fish[Gear  > 0, Gear ]) + 1]
  
  fish.out <- c()
  for(i in 1:length(group)){
    fish.group <- fish[Group == group[i], ]
    fish.all.gear <- data.table(Group = group.name[i])
    for(j in 1:length(gear)){
      f.gear <- data.table(Group = group.name[i], V1 = fish.group[Gear == gear[j], sum(Q)])
      setnames(f.gear, 'V1', gear.name[j])
      fish.all.gear <- merge(fish.all.gear, f.gear, by = 'Group')
    }
    fish.out <- rbindlist(list(fish.out, fish.all.gear))
  }
  fish.out[, Total := rowSums(.SD), .SDcols = gear.name]
  return(fish.out)
}

#'Adjust Fishing Mortality
#'
#'Modifies the fishing mortality value for a species by a particular gear.
#'
#'@family Rpath functions
#'
#'@param Rpath.sim Object generated by ecosim.init.
#'@param group Name or number of the species group whose fishing mortality rate 
#'is being changed.
#'@param gear Name or number of the gear to which the change applies.
#'@param frate New fishing mortality rate.  Can be an actual value or a multiplier.
#'@param multiplier Logical value indicating whether or not the frate is a multiplier.
#'@param target Logical value indicating whether the change effects landings mortality.
#'@param discard Logical value indicating whether the change effects discard mortality.
#'
#'@return Returns an Rpath.sim object with the new F rate.
#'@export 
frate.adjust <- function(Rpath.sim, group, gear, frate, multiplier = T, target = T, discard = T){
  #Convert group/gear names to number if necessary
  if(is.character(group)){
    group <- which(Rpath.sim$spname == group) - 1
    if(length(group) == 0) stop('Group not found')
  }
  if(is.character(gear)){
    gear  <- which(Rpath.sim$spname == gear)  - 1
    if(length(gear) == 0) stop('Gear not found')
  }
  
  #Create fishing table
  fish <- data.table(Group = Rpath.sim$FishFrom,
                     Gear  = Rpath.sim$FishThrough,
                     Fate  = Rpath.sim$FishTo,
                     Q     = Rpath.sim$FishQ)
  
  if(multiplier == T){
    if(target  == T) fish[Group == group & Gear == gear & Fate == 0, Q := Q * frate]
    if(discard == T) fish[Group == group & Gear == gear & Fate >  0, Q := Q * frate]
  } else {
    if(target  == T) fish[Group == group & Gear == gear & Fate == 0, Q := frate]
    if(discard == T) fish[Group == group & Gear == gear & Fate >  0, Q := frate]
  }
  Rpath.sim$FishQ <- fish[, Q]
}





