#'Mixed Trophic Impacts
#'
#'Need to edit.
#'
#'@family Rpath functions
#'
#'@param Rpath Balanced Rpath model generated by rpath.
#'@param Rpath.params R object containing the Rpath parameters.  This is generated
#'  either by the create.rpath.params or read.rpath.params functions.
#'
#'@return Returns a matrix of mixed trophic impacts.
#'@export 
MTI <- function(Rpath, Rpath.params){
  x <- copy(Rpath.params)
  f.dc <- data.table(Fishing = rep(0, nrow(x$diet)))
  DC <- as.data.table(cbind(f.dc, x$diet))
  DC <- DC[Group != 'Import']
  DC[, Group := NULL]
  
  #Need to make write functions able to output to RData
  y <- copy(Rpath)
  ngroup <- y$NUM_LIVING + y$NUM_DEAD
  
  #Calculate F mortality
  totcatch <- y$Catch + y$Discards
  Fmort    <- as.data.frame(totcatch / y$BB[row(as.matrix(totcatch))])
  setnames(Fmort, paste0('V',  seq_along(y$NUM_GEARS)),
           paste0('F.', y$Group[(ngroup +1):y$NUM_GROUPS]))
  Fmort <- Fmort[1:ngroup, ]
  
  #Calculate M2
  bio  <- y$BB[1:y$NUM_LIVING]
  BQB  <- bio * y$QB[1:y$NUM_LIVING]
  diet <- as.data.frame(y$DC)
  nodetrdiet <- diet[1:y$NUM_LIVING, ]
  detrdiet   <- diet[(y$NUM_LIVING +1):ngroup, ]
  newcons    <- nodetrdiet * BQB[col(as.matrix(nodetrdiet))]
  predM      <- newcons / bio[row(as.matrix(newcons))]
  detcons    <- detrdiet * BQB[col(as.matrix(detrdiet))]
  predM      <- rbind(predM, detcons)
  setnames(predM, paste('V',  1:y$NUM_LIVING,    sep = ''),
           paste('M2.', y$Group[1:y$NUM_LIVING], sep = ''))
  
  FC <- as.data.table(cbind(Fmort, predM))
  
  FC[, mort.sum := rowSums(.SD), .SDcols = names(FC)]
  FC <- FC[, .SD / mort.sum, .SDcols = names(FC)]
  FC[, mort.sum := NULL]
  
  #Merge pred and prey
  MTI <- as.matrix(DC + FC)
  
  #Add small increase
  MTI.diag <- diag(MTI) + 1
  
  diag(MTI) <- MTI.diag
  
  #Inverse
  out <- MASS::ginv(MTI)
  
  return(out)
}






