#'Mixed Trophic Impacts
#'
#'Need to edit.
#'
#'@family Rpath functions
#'
#'@param Rpath Balanced Rpath model generated by rpath.
#'@param Rpath.params R object containing the Rpath parameters.  This is generated
#'  either by the create.rpath.params or read.rpath.params functions.
#'@param increase Logical value indicating whether a marginal increase is applied.
#'
#'@return Returns a matrix of mixed trophic impacts.
#'@export 
MTI <- function(Rpath, Rpath.params, increase = T){
  x <- copy(Rpath.params)
  y <- copy(Rpath)
  
  #MTI is a matrix where MTIij = DCij - FCji
  #Get number of fleets and detrital groups
  nfleets       <- length(which(x$model$Type == 3))
  ndetritus     <- length(which(x$model$Type == 2))
  ngroups       <- length(x$model$Group)
  fleetnames    <- x$model$Group[which(x$model$Type == 3)]
  detritusnames <- x$model$Group[which(x$model$Type == 2)]
  allnames      <- x$model$Group
  
  #Set up DCij including detritus and fleet
  DC <- as.data.table(x$diet)
  newcols <- as.data.table(matrix(rep(0, (nfleets + ndetritus) * ngroups),
                           ngroups, nfleets + ndetritus))
  setnames(newcols, paste0('V', seq_along(c(detritusnames, fleetnames))),
                           c(detritusnames, fleetnames))
  DC <- cbind(DC, newcols)
  
  #Remove import and re-standardize remaining DC
  DC <- DC[Group != 'Import']
  DC.colsum <- DC[, colSums(.SD, na.rm = T), .SDcols = allnames]
  for(icol in 1:length(allnames)){
    if(round(DC.colsum[icol], 4) != 1){
      DC[, icol + 1 := .SD/DC.colsum[icol], .SDcols = allnames[icol]]
    }
  }
  #Fix NAs
  DC[is.na(DC)] <- 0
  
  #Add fleet "prey" rows
  fleetrows <- as.data.table(matrix(rep(0, nfleets * ncol(DC)), nfleets, 
                                    ncol(DC)))
  fleetrows[, V1 := fleetnames]
  DC <- rbindlist(list(DC, fleetrows))
  
  #Calculate proportion of catch for fishing "DC"
  totcatch <- y$Catch + y$Discards
  totcatch.sum <- colSums(totcatch)
  for(icol in 1:ncol(totcatch)){
    fleet.prop <- as.data.table(totcatch[, icol] / totcatch.sum[icol])
    setnames(fleet.prop, 'V1', fleetnames[icol])
    if(icol == 1){
      totcatch.prop <- fleet.prop
    }else{
      totcatch.prop <- cbind(totcatch.prop, fleet.prop)
    }
  }
  #Remove dummy Fishery columns and add actual "DC"
  setnames(DC, fleetnames, paste0('V', seq_along(fleetnames)))
  DC[, paste0('V', seq_along(fleetnames)) := NULL]
  DC <- cbind(DC, totcatch.prop)
  
  #Ensure column order is correct
  matrix.order <- c('Group', DC$Group)
  setcolorder(DC, matrix.order)
  
  #Remove Group names
  DC[, Group := NULL]
  
  
  #FCji - Proportion of predation on j from predator i
  #Calculate consumption
  bio  <- y$BB
  BQB  <- bio * y$QB
  Tij <- DC * BQB[col(as.matrix(DC))]
  
  #Add fishery removals
  setnames(Tij, fleetnames, paste0('V', seq_along(fleetnames)))
  Tij[, paste0('V', seq_along(fleetnames)) := NULL]
  Tij <- cbind(Tij, totcatch)
  setnames(Tij, paste0('V', seq_along(fleetnames)), fleetnames)
  
  #Calculate net production
  Tim <- rowSums(Tij)
  
  #Calculate fraction of i's production consumed by pred j
  FCij <- c()
  for(i in 1:nrow(Tij)){
    fij <- Tij[i, ] / Tim[i]
    FCij <- rbind(FCij, fij)
  }
  FCji <- t(FCij)
  FCji[is.na(FCji)] <- 0
 
  #Merge pred and prey
  MTI <- as.matrix(DC - FCji)
  
  #Add small increase
  if(increase == T){
    MTI.diag <- diag(MTI) + 1
  }else{
    MTI.diag <- diag(MTI) - 1
  }
  
  diag(MTI) <- MTI.diag
  
  #Inverse
  out <- MASS::ginv(MTI)
  
  return(out)
}






