# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Adams_test <- function(params, instate, forcing, fishing, StartYear, EndYear) {
    .Call('Rpath_Adams_test', PACKAGE = 'Rpath', params, instate, forcing, fishing, StartYear, EndYear)
}

deriv_test <- function(params, state, forcing, fishing, y, m, d) {
    .Call('Rpath_deriv_test', PACKAGE = 'Rpath', params, state, forcing, fishing, y, m, d)
}

deriv_master <- function(mod, y, m, d) {
    .Call('Rpath_deriv_master', PACKAGE = 'Rpath', mod, y, m, d)
}

SplitSetPred <- function(mod) {
    .Call('Rpath_SplitSetPred', PACKAGE = 'Rpath', mod)
}

update_stanzas <- function(mod, yr, mon) {
    .Call('Rpath_update_stanzas', PACKAGE = 'Rpath', mod, yr, mon)
}

Adams_Basforth <- function(mod, StartYear, EndYear) {
    .Call('Rpath_Adams_Basforth', PACKAGE = 'Rpath', mod, StartYear, EndYear)
}

vpow <- function(base, exp) {
    .Call('Rpath_vpow', PACKAGE = 'Rpath', base, exp)
}

