---
name: Bug report
description: Use this template to report bugs
title: "[Bug Report]:"
labels: "[bug]"
assignees: ''
---

body:
  - type: markdown
    attributes:
      value: |
        Please use the fields below to describe the bug. We will need this information to reproduce and fix any issues. Thanks
  - type: textarea
    id: bugdesc
    attributes:
      label: **Describe the bug**
      description: A clear and concise description of what the bug is.
    validations:
      required: true
