name: Feature Request
description: Suggest an idea to help us improve
title: "[Feature]: "
labels: ["feature"]

body:
  - type: markdown
    attributes:
      value: >
        **Thanks for taking the time to fill out this feature request report!** We kindly ask that you search
        the current issues to see if an issue [already exists](https://github.com/NOAA-EDAB/Rpath/issues?q=is%3Aissue%20state%3Aopen%20label%3Afeature)
        for your feature.

        We are also happy to accept contributions from our users. For more details see
        [here](https://github.com/Rpath/CONTRIBUTING.md).

  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in.
      value: |
        <!--- Describe your feature here --->
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: >
        Describe the solution you'd like. A clear and concise description of what you want to happen. If you have
        considered alternatives, please describe them.
      value: |
        <!--- Describe your solution here --->
    validations:
      required: false