#'Adjust Forcing Parameters
#'
#'Modifies the various forcing parameters of the rsim scenario object.
#'
#'@family Rpath functions
#'
#'@param Rsim.scenario Object generated by rsim.scenario.
#'@param parameter The Rsim.scenario forcing parameter to be modified. 
#'@param group The model group that the parameter change will affect.
#'@param sim.year Year of the simulation that should be modified.  Can be a range of years.
#'@param sim.month Month of the year that should be modified.  If set to 0, all months of
#'             the year are modified.
#'@param bymonth Boolean value that denotes whether to use sim.year/sim.month combo
#'               or just sim.month as a sequential vector starting at 1.
#'@param value The new value for the parameter.
#'@return Returns an Rsim.scenario object with the new parameter.
#'@export 
adjust.forcing <- function(Rsim.scenario, parameter, group, sim.year = 1, sim.month = 0, 
                           bymonth = F, value){
  #Check that parameter and group exist
  if(!parameter %in% c('ForcedPrey', 'ForcedMort', 'ForcedRecs', 'ForcedSearch', 'ForcedActresp',  
                       'ForcedMigrate', 'ForcedBio')){stop("Forcing parameter not found")}
  if(!all(group %in% Rsim.scenario$params$spname)){
    stop("Groups not found:",group[!(group %in% Rsim.scenario$params$spname)])
  }
  #if(!group %in% Rsim.scenario$params$spname){stop("Group not found")}
  
  if(bymonth){
    Rsim.scenario$forcing[[parameter]][sim.month, group] <- value
  }else {
    
    #Create index in case the number of values is equal to length(sim.year) * length(sim.month)
    ivalue <- 0 
    
    #Loop over years if more than 1 sim.year provided
    for(iyear in seq_along(sim.year)){
      for(imonth in seq_along(sim.month)){
        ivalue <- ivalue + 1
        #look-up what rows correspond to the year
        #Regex used to account for year.month row names in Effort Matrix
        year.row <- which(gsub("\\..*", "", rownames(Rsim.scenario$forcing[[parameter]]))
                          == sim.year[iyear])
        
        #identify what rows correspond to the sim.months - 0 indicates the whole year
        if(sim.month[1] != 0){
          year.row <- year.row[1:12 %in% sim.month[imonth]]
        }
        
        #Apply the value to the correct row
        if(length(value) == 1){
          #If only 1 value is supplied for multiple years need to only point to that value
          Rsim.scenario$forcing[[parameter]][year.row, group] <- value
        }else if(sim.month[1] == 0){
          Rsim.scenario$forcing[[parameter]][year.row, group] <- value[iyear]
        }else if(length(value) == length(sim.month)){
          Rsim.scenario$forcing[[parameter]][year.row, group] <- value[imonth]
        }else {
          Rsim.scenario$forcing[[parameter]][year.row, group] <- value[ivalue]
        }
      }
    }
  }
  
  return(Rsim.scenario)
}