#'Run Rsim
#'
#'Carries out the numerical integration of the Rsim alogrithms. 
#'
#'@import utils
#'@import stats
#'@family Rsim functions
#'
#'@inheritParams rsim.scenario
#'@param Rsim.scenario Scenario object that contains all of the rsim rates and 
#'    forcing functions generated by \code{rsim.scenario}.
#'@param method Numerical integration method. Either \emph{'AB'} for Adams-Bashforth or 
#'   \emph{'RK4'} for 4th order Runge-Kutta.
#'   
#'@export
#'
rsim.run <- function(Rsim.scenario, method = 'RK4', years = 1:100){
  scene <- copy(Rsim.scenario) 
  
  # Figure out starting and ending years for run
  # KYA 4/23/18 single year (e.g. 1971:1971) reduces to a scalar so take out length trap
  #if (length(years)<2){stop("Years should be a vector of year labels")}
  scene.years <- row.names(Rsim.scenario$fishing$ForcedFRate)
  syear <- which(as.character(head(years,1))==scene.years)
  eyear <- which(as.character(tail(years,1))==scene.years)
  if (eyear<syear)     {stop("End year cannot be less than start year.")}
  if (length(syear)!=1){stop("Starting year not found in scenario (or more than once).")}
  if (length(eyear)!=1){stop("Ending year not found in scenario (or more than once).")}
  
  # KYA adds run date and some random salt to ensure uniquieness  
  scene$rundate <- paste(Sys.time(),":salt:",runif(1))    
  
  if(method == 'RK4'){
    rout <- rk4_run(scene$params,  scene$start_state, 
                    scene$forcing, scene$fishing,
                    scene$stanzas, syear, eyear)
  }
  if(method == 'AB'){
    #Run initial derivative
    derv <- deriv_vector(scene$params, scene$start_state, 
                         scene$forcing, scene$fishing, 
                         scene$stanzas, syear, 0, 0)
    #KYA added for first step bump correction 9/20/17
    
    #Run Adams Bashforth Alogrithm
    rout <- Adams_run(scene$params,  scene$start_state, 
                      scene$forcing, scene$fishing,
                      scene$stanzas, syear, eyear, derv)
  }
  # Nicely Name output vectors
  sps <- scene$params$spname[1:(1+scene$params$NUM_BIO)]
  colnames(rout$out_Biomass)    <- sps
  colnames(rout$out_Catch)    <- sps
  colnames(rout$annual_Catch) <- sps
  colnames(rout$annual_Biomass) <- sps
  colnames(rout$annual_QB) <- sps
  colnames(rout$annual_Qlink)<-1:(length(rout$annual_Qlink[1,]))
  
  # drop the last row (should be always 0; negative index is entry to drop)
  #lastone <- length(rout$annual_Catch[,1])
  #rout$annual_Catch <-    rout$annual_Catch[-lastone,]
  #rout$annual_Biomass <-    rout$annual_Biomass[-lastone,]
  #rout$annual_QB <-    rout$annual_QB[-lastone,]
  #rout$annual_Qlink <- rout$annual_Qlink[-lastone,]  
  
  #if(!is.null(Rsim.scenario$fitting$years)){
  #  ylist <- seq(scene$fitting$years[1],length.out=length(rout$annual_Catch[,1]))
  # put years in row names
  ys <- min(as.numeric(rownames(scene$fishing$ForcedCatch)))
  ylist <- seq(ys,length.out=length(rout$annual_Catch[,1]))
  rownames(rout$annual_Catch) <-    ylist #Rsim.scenario$fitting$years
  rownames(rout$annual_Biomass) <-    ylist #Rsim.scenario$fitting$years
  rownames(rout$annual_QB) <-    ylist #Rsim.scenario$fitting$years
  rownames(rout$annual_Qlink) <- ylist #Rsim.scenario$fitting$years   
  #}
  
  rout$pred <- scene$params$spname[scene$params$PreyTo+1] 
  rout$prey <- scene$params$spname[scene$params$PreyFrom+1] 
  rout$Gear_Catch_sp   <- scene$params$spname[scene$params$FishFrom+1] 
  rout$Gear_Catch_gear <- scene$params$spname[scene$params$FishThrough+1] 
  rout$Gear_Catch_disp <- ifelse(scene$params$FishTo == 0, 'Landing', 'Discard')
  
  rout$start_state       <- scene$start_state
  rout$params$NUM_LIVING <- scene$params$NUM_LIVING
  rout$params$NUM_DEAD   <- scene$params$NUM_DEAD
  rout$params$NUM_GEARS  <- scene$params$NUM_GEARS
  rout$params$spname     <- scene$params$spname
  
  class(rout) <- 'Rsim.output'
  attr(rout, 'eco.name') <- attr(scene, 'eco.name')
  
  return(rout)
}