#'Write function for Rpath food web object
#'
#'Outputs basic parameters or mortalities from a \code{rpath()} object to a .csv or .RData file.
#'
#'@family Rpath functions
#'
#'@param x Rpath model object generated by \code{rpath()}.
#'@param file file name for resultant file.  Need to specify ".csv" or ".RData".
#'@param morts Logical value whether to output basic parameters or mortalities.  
#'
#'
#'@return Writes a list object or file with the basic parameters or mortalities from an Rpath object.
#' # If morts = F, output reflects the basic parameters of the mass-balanced model, namely:
#'\item{Group}{Vector of group names}
#'\item{type}{Vector of group types: 0 = consumer, 1 = producer, 2 = detritus, 3 = fishery}
#'\item{TL}{Vector of trophic level for each group, calculated based on mass balance}
#'\item{Biomass}{Vector of biomass values for each modeled group}
#'\item{PB}{Vector of production:biomass ratios for each modeled group}
#'\item{QB}{Vector of consumption:biomass ratios for each modeled group}
#'\item{EE}{Vector of ecotrophic efficiency values for each modeled group}
#'\item{GE}{Vector of gross efficiency values (production:comsumption ratios) for each modeled group}
#'\item{Removals}{Vector of total fishery removals for each modeled group}
#'
#'# If morts = T, output reflects calculated mortality values for each group. 
#'# The number of columns will vary based on how many predators are in the model.
#'\item{Group}{Vector of group names}
#'\item{M0}{Vector of natural mortality for each group. Natural mortality = PB * (1-EE)}
#'\item{Fmort}{Vector of fishing mortality for each group}
#'\item{M2.XX}{Vector of predation mortality, where XX is the name of a predator group}
#'
#'
#'@examples
#' # Read in Rpath parameter file, generate model object
#' x <- rpath(AB.params)
#' # Saves basic model parameters for all groups to the root directory of users project
#' write.Rpath(x, file = "output.csv", morts = F)
#' # Calculates natural mortality (M0), fishing mortality by fleet, and predation mortality by predator (M2) on each group
#' # Writes output to an Rdata file in the root directory of users project
#' write.Rpath(x, file = here::here("output.RData"), morts = T)
#' 
#' 
#'@import utils
#'@import data.table
#'
#'
#'@export

#Write -- note, not a generic function
write.Rpath <- function(x, file = NA, morts = F){
  #Check extention for output type - if not supplied a .csv or .RData the output
  #will be saved as a list object
  ext <- 'list'
  if(grepl('.csv', file) == T) ext <- 'csv'
  if(grepl('.RData', file, ignore.case = T) == T) ext <- 'RData'
  
  if(morts == F){
    removals <- rowSums(x$Landings) + rowSums(x$Discard)
    out <- data.frame(Group    = x$Group,
                      type     = x$type,
                      TL       = x$TL,
                      Biomass  = x$Biomass,
                      PB       = x$PB,
                      QB       = x$QB,
                      EE       = x$EE,
                      GE       = x$GE,
                      Removals = removals)
  }
  if(morts == T){
    ngroup <- x$NUM_LIVING + x$NUM_DEAD
    out <- data.frame(Group    = x$Group[1:ngroup],
                      type     = x$type [1:ngroup],
                      PB       = x$PB   [1:ngroup])
    #Calculate M0
    M0  <- c(x$PB[1:x$NUM_LIVING] * (1 - x$EE[1:x$NUM_LIVING]), 
             x$EE[(x$NUM_LIVING + 1):ngroup])
    out <- cbind(out, M0)
    #Calculate F mortality
    totcatch <- x$Landings + x$Discards
    Fmort    <- as.data.frame(totcatch / x$Biomass[row(as.matrix(totcatch))])
    out  <- cbind(out, Fmort[1:ngroup, ])
    #Calculate M2
    bio  <- x$Biomass[1:x$NUM_LIVING]
    BQB  <- bio * x$QB[1:x$NUM_LIVING]
    diet <- as.data.frame(x$DC)
    nodetrdiet <- diet[1:x$NUM_LIVING, ]
    detrdiet   <- diet[(x$NUM_LIVING +1):ngroup, ]
    newcons    <- nodetrdiet * BQB[col(as.matrix(nodetrdiet))]
    predM      <- newcons / bio[row(as.matrix(newcons))]
    detcons    <- detrdiet * BQB[col(as.matrix(detrdiet))]
    predM      <- rbind(predM, detcons)
    setnames(predM, names(predM), paste0('M2.', names(predM)))
    out <- cbind(out, predM)
  }
  if(ext == 'csv')   write.csv(out, file = file)
  if(ext == 'RData') save(out, file = file)
  if(ext == 'list')  return(out)
}


#'Write function for Rsim run
#'
#'Outputs starting biomass, ending biomass, and catch to a .csv file.
#'
#'@family Rsim functions
#'
#'@param Rsim.output object created by the \code{rsim.run()} function.
#'@param file file name for resultant file.  Need to specify ".csv" or ".RData".  
#'
#'@return Writes a list object or file with the start and end biomass and catch per group
#' from an Rpath.sim object.
#' \item{Group}{Vector of group names}
#' \item{StartBio}{Vector of Biomass values at simulation start}
#' \item{EndBio}{Vector of Biomass values at simulation end}
#' \item{BioES}{Vector of ratio end:start Biomass values}
#' \item{StartCatch}{Vector of Catch values at simulation start}
#' \item{EndCatch}{Vector of Catch values at simulation end}
#' \item{CatchES}{Vector of ratio end:start Catch values}
#' 
#' @examples
#' # Read in Rpath parameter file and generate model object
#' Rpath <- rpath(AB.params)
#' # Create a 50 yr Rsim scenario
#' Rsim.scenario <- rsim.scenario(Rpath, AB.params, years = 1:50)
#' # Run the Rsim simulation
#' Rsim.output <- rsim.run(Rsim.scenario, method = "RK4", years = 1:50)
#' # Save summary output to a .csv file
#' write.Rsim(Rsim.output, file = "output.csv")
#' 
#' 
#'@import utils
#'@export

#Write -- note, not a generic function
write.Rsim <- function(Rsim.output, file = NA){
  #Check extention for output type - if not supplied a .csv or .RData the output
  #will be saved as a list object
  ext <- 'list'
  if(grepl('.csv', file) == T) ext <- 'csv'
  if(grepl('.RData', file, ignore.case = T) == T) ext <- 'RData'
  
  gear.zero <- rep(0, Rsim.output$params$NUM_GEARS)
  start_Catch <- c(Rsim.output$out_Catch[2, ], gear.zero)
  end_Catch   <- c(Rsim.output$out_Catch[nrow(Rsim.output$out_Catch) - 1, ], gear.zero)
  out <- data.frame(Group      = Rsim.output$params$spname,
                    StartBio   = Rsim.output$start_state$Biomass,
                    EndBio     = Rsim.output$end_state$Biomass,
                    BioES      = Rsim.output$end_state$Biomass / 
                                 Rsim.output$start_state$Biomass,
                    StartCatch = start_Catch * 12,
                    EndCatch   = end_Catch * 12,
                    CatchES    = (end_Catch * 12) / (start_Catch * 12))
  if(ext == 'csv')   write.csv(out, file = file)
  if(ext == 'RData') save(out, file = file)
  if(ext == 'list')  return(out)
}
